export type CalendarBooking={id?:number;service:string;barber:string;date:string;time:string;duration:number;price?:number;name:string;email:string;phone:string};
const SHOP='LuxuryCuts';const LOCATION='LuxuryCuts, 21 Bree Street, Cape Town, 8001, South Africa';const SHOP_CONTACT='+27 21 555 0147 · hello@luxurycuts.co.za';
// Appointments are in shop time (Africa/Johannesburg, UTC+2, no DST), so convert to UTC for every calendar client
function startDate(b:CalendarBooking){const [y,m,d]=b.date.split('-').map(Number);const [h,min]=b.time.split(':').map(Number);return new Date(Date.UTC(y,m-1,d,h-2,min))}
function pad(n:number){return String(n).padStart(2,'0')}
function utcStamp(d:Date){return `${d.getUTCFullYear()}${pad(d.getUTCMonth()+1)}${pad(d.getUTCDate())}T${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}${pad(d.getUTCSeconds())}Z`}
function range(b:CalendarBooking){const s=startDate(b);return {s,e:new Date(s.getTime()+b.duration*60000)}}
function title(b:CalendarBooking){return `${SHOP} — ${b.service} with ${b.barber}`}
function details(b:CalendarBooking){return [`${b.service} with ${b.barber} (${b.duration} min${b.price?`, R${b.price}`:''})`,`Booked for ${b.name} · ${b.phone}`,b.id?`Booking reference: LC-${b.id}`:'','Please arrive 5 minutes early. 24 hours notice is required to cancel or reschedule.',`Questions? ${SHOP_CONTACT}`].filter(Boolean).join('\n')}
export function googleCalendarUrl(b:CalendarBooking){const {s,e}=range(b);const p=new URLSearchParams({action:'TEMPLATE',text:title(b),dates:`${utcStamp(s)}/${utcStamp(e)}`,details:details(b),location:LOCATION,ctz:'Africa/Johannesburg'});return `https://calendar.google.com/calendar/render?${p}`}
function esc(t:string){return t.replace(/\\/g,'\\\\').replace(/;/g,'\\;').replace(/,/g,'\\,').replace(/\r?\n/g,'\\n')}
// RFC 5545 lines must be folded at 75 octets
function fold(line:string){const out:string[]=[];let cur='',len=0;for(const ch of line){const n=new TextEncoder().encode(ch).length;if(len+n>(out.length?74:75)){out.push(cur);cur='';len=0}cur+=ch;len+=n}out.push(cur);return out.join('\r\n ')}
export function icsContent(b:CalendarBooking){const {s,e}=range(b);return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//LuxuryCuts//Booking//EN','CALSCALE:GREGORIAN','METHOD:PUBLISH','BEGIN:VEVENT',`UID:luxurycuts-${b.id??Date.now()}-${b.date}-${b.time.replace(':','')}@luxurycuts.co.za`,`DTSTAMP:${utcStamp(new Date())}`,`DTSTART:${utcStamp(s)}`,`DTEND:${utcStamp(e)}`,`SUMMARY:${esc(title(b))}`,`DESCRIPTION:${esc(details(b))}`,`LOCATION:${esc(LOCATION)}`,'STATUS:CONFIRMED','BEGIN:VALARM','ACTION:DISPLAY','DESCRIPTION:Appointment reminder','TRIGGER:-PT1H','END:VALARM','END:VEVENT','END:VCALENDAR'].map(fold).join('\r\n')+'\r\n'}
export function downloadICS(b:CalendarBooking){const blob=new Blob([icsContent(b)],{type:'text/calendar;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`luxurycuts-${b.date}-${b.time.replace(':','')}.ics`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
