import {useEffect,useState} from 'react';import {X} from 'lucide-react';import {Link,useLocation} from 'react-router-dom';
const KEY='luxurycuts-promo-dismissed';
function dismissed(){try{return sessionStorage.getItem(KEY)==='1'}catch{return false}}
export default function PromoModal(){const {pathname}=useLocation();const [show,setShow]=useState(false);
// Show once per visit, shortly after landing, and never over the booking or legal pages
useEffect(()=>{if(dismissed()||['/booking','/terms'].includes(pathname))return;const t=setTimeout(()=>setShow(true),1500);return()=>clearTimeout(t)},[pathname]);
const close=()=>{setShow(false);try{sessionStorage.setItem(KEY,'1')}catch{}};
useEffect(()=>{if(!show)return;const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')close()};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[show]);
if(!show)return null;return <div onClick={close} className="fixed inset-0 z-[60] bg-black/70 backdrop-blur-sm grid place-items-center p-5"><div role="dialog" aria-modal="true" aria-labelledby="promo-title" onClick={e=>e.stopPropagation()} className="relative max-w-md w-full bg-[#151515] border border-[#c9a96e33] p-8 rounded-3xl shadow-2xl"><button autoFocus onClick={close} aria-label="Close offer" className="absolute right-4 top-4 text-white/50 hover:text-white"><X/></button><div className="text-xs uppercase tracking-[.25em] gold">First visit</div><h2 id="promo-title" className="font-display text-4xl font-bold mt-3">A little extra off.</h2><p className="text-white/60 leading-7 mt-4">New to LuxuryCuts? Enjoy 15% off your first appointment. Just mention this offer when you arrive.</p><div className="flex flex-wrap items-center gap-4 mt-7"><Link onClick={close} to="/booking" className="btn-gold">Book your first cut</Link><button onClick={close} className="text-sm text-white/45 hover:text-white">Maybe later</button></div></div></div>}
